version: '3.9'

services:
  mongodb:
    image: mongo:7-jammy
    container_name: stock-mgmt-mongodb-prod
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: stock-management
    volumes:
      - mongodb_prod_data:/data/db
      - mongodb_prod_config:/data/configdb
      - ./scripts/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    networks:
      - stock-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/stock-management --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
      target: production
    container_name: stock-mgmt-backend-prod
    restart: always
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongodb:27017/stock-management?authSource=admin
      PORT: 3001
    env_file:
      - ../apps/backend/.env.production
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - stock-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/api/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3001/api}
    container_name: stock-mgmt-frontend-prod
    restart: always
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    networks:
      - stock-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongodb_prod_data:
    driver: local
  mongodb_prod_config:
    driver: local

networks:
  stock-network:
    driver: bridge
